import Transformers from "./Transformers.type";
import {
  Annotation,
  EachOf,
  IRIREF,
  IriStem,
  IriStemRange,
  LANGTAG,
  Language,
  LanguageStem,
  LanguageStemRange,
  LiteralStem,
  LiteralStemRange,
  NodeConstraint,
  ObjectLiteral,
  OneOf,
  Schema,
  SemAct,
  Shape,
  ShapeAnd,
  shapeExprRef,
  ShapeExternal,
  ShapeNot,
  ShapeOr,
  STRING,
  TripleConstraint,
  tripleExprRef,
  Wildcard,
} from "shexj";
import traverseSchema from "./traversers/traverseSchema";
import defaultTransformers from "./defaultTransformers";

export default function traverseShex<Return>(
  shexSchema: Schema,
  transformers: Partial<
    Transformers<
      SchemaReturn,
      ShapeOrReturn,
      ShapeAndReturn,
      ShapeNotReturn,
      ShapeExternalReturn,
      NodeConstraintReturn,
      ObjectLiteralReturn,
      IriStemReturn,
      IriStemRangeReturn,
      LiteralStemReturn,
      LiteralStemRangeReturn,
      LanguageReturn,
      LanguageStemReturn,
      LanguageStemRangeReturn,
      WildcardReturn,
      ShapeReturn,
      EachOfReturn,
      OneOfReturn,
      TripleConstraintReturn,
      SemActReturn,
      AnnotationReturn,
      shapeExprReturn,
      valueSetValueReturn,
      tripleExprReturn,
      Schema_startActsReturn,
      Schema_startReturn,
      Schema_shapesReturn,
      ShapeOr_shapeExprsReturn,
      ShapeAnd_shapeExprsReturn,
      ShapeNot_shapeExprReturn,
      NodeConstraint_valuesReturn,
      IriStemRange_exclusionsReturn,
      LiteralStemRange_exclusionsReturn,
      LanguageStemRange_exclusionsReturn,
      Shape_expressionReturn,
      Shape_semActsReturn,
      Shape_AnnotationsReturn,
      EachOf_expressionsReturn,
      EachOf_semActsReturn,
      EachOf_AnnotationsReturn,
      OneOf_expressionsReturn,
      OneOf_semActsReturn,
      OneOf_AnnotationsReturn,
      TripleConstraint_valueExprReturn,
      TripleConstraint_semActsReturn,
      TripleConstraint_AnnotationsReturn
    >
  >
) {
  const combinedTransformers: Transformers<
    SchemaReturn,
    ShapeOrReturn,
    ShapeAndReturn,
    ShapeNotReturn,
    ShapeExternalReturn,
    NodeConstraintReturn,
    ObjectLiteralReturn,
    IriStemReturn,
    IriStemRangeReturn,
    LiteralStemReturn,
    LiteralStemRangeReturn,
    LanguageReturn,
    LanguageStemReturn,
    LanguageStemRangeReturn,
    WildcardReturn,
    ShapeReturn,
    EachOfReturn,
    OneOfReturn,
    TripleConstraintReturn,
    SemActReturn,
    AnnotationReturn,
    shapeExprReturn,
    valueSetValueReturn,
    tripleExprReturn,
    Schema_startActsReturn,
    Schema_startReturn,
    Schema_shapesReturn,
    ShapeOr_shapeExprsReturn,
    ShapeAnd_shapeExprsReturn,
    ShapeNot_shapeExprReturn,
    NodeConstraint_valuesReturn,
    IriStemRange_exclusionsReturn,
    LiteralStemRange_exclusionsReturn,
    LanguageStemRange_exclusionsReturn,
    Shape_expressionReturn,
    Shape_semActsReturn,
    Shape_AnnotationsReturn,
    EachOf_expressionsReturn,
    EachOf_semActsReturn,
    EachOf_AnnotationsReturn,
    OneOf_expressionsReturn,
    OneOf_semActsReturn,
    OneOf_AnnotationsReturn,
    TripleConstraint_valueExprReturn,
    TripleConstraint_semActsReturn,
    TripleConstraint_AnnotationsReturn
  > = Object.assign(defaultTransformers, transformers);
  return traverseSchema(shexSchema, combinedTransformers);
}
